language: c

compiler:
  - gcc
  - clang

services: mongodb

env:
  - CFLAGS="$CFLAGS -Werror -Wno-cast-align" 

script:
  - ./autogen.sh --enable-maintainer-flags --disable-automatic-init-and-cleanup --with-libbson=bundled
  - make
  - make test

